//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LitShopEntities : DbContext
    {
        public LitShopEntities()
            : base("name=LitShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TGoods> TGoods { get; set; }
        public DbSet<TGoodsType> TGoodsType { get; set; }
        public DbSet<TOrder> TOrder { get; set; }
        public DbSet<TOrderDetails> TOrderDetails { get; set; }
        public DbSet<TSystemMessage> TSystemMessage { get; set; }
        public DbSet<TToday_Special_Offer> TToday_Special_Offer { get; set; }
        public DbSet<TUser> TUser { get; set; }
        public DbSet<TUserCarts> TUserCarts { get; set; }
        public DbSet<TFeedback> TFeedback { get; set; }
    }
}
